### Hello
POST http://localhost:3000/exec/faas-modules/hello_faas.wasm
Content-Type: application/json

{
  "name": "Toni"
}

### Fibonacci
POST http://localhost:3000/exec/faas-modules/fibonacci_faas.wasm
Content-Type: application/json

{
  "n": 7
}

### S3
POST http://localhost:3000/exec/faas-modules/s3_faas.wasm
Content-Type: application/json

{
  "bucket": "faas-modules"
}